// import type { Metadata } from "next";
// import Header from "@/components/Tools/Header";
// import { Footer } from "@/components/Tools/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>
//       <Header />
//       <main className="pt-16">{children}</main>
//       <Footer />
//     </div>
//   );
// }



// // app/layout.tsx
// import type { Metadata } from 'next'
// import Header from '@/components/Tools/Header'
// import { Footer } from '@/components/Tools/Footer'
// import { ReactNode } from 'react'
// import { AnimatePresence } from 'framer-motion'
// import PageWrapper from './PageWrapper' // This is the motion wrapper

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: ReactNode
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <Header />
//         <main className="pt-16">
//           {/* AnimatePresence needs to be client-side */}
//           <AnimatePresence mode="wait">
//             <PageWrapper>{children}</PageWrapper>
//           </AnimatePresence>
//         </main>
//         <Footer />
//       </body>
//     </html>
//   )
// }


// // app/(main)/(client)/layout.tsx
// import type { Metadata } from 'next'
// import ClientLayout from '@/components/ClientLayout'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return <ClientLayout>{children}</ClientLayout>
// }

// // app/layout.tsx
// import type { Metadata } from 'next'
// import TransitionLayout from '@/components/TransitionLayout'

// export const metadata: Metadata = {
//   title: 'Smooth Transitions App',
//   description: 'With animated splash between pages',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <TransitionLayout>{children}</TransitionLayout>
//       </body>
//     </html>
//   )
// }



// app/(main)/layout.tsx
import type { Metadata } from 'next'
import TransitionLayout from '@/components/TransitionLayout'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Smooth animated splash',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TransitionLayout>{children}</TransitionLayout>
      </body>
    </html>
  )
}
