import type { Metadata } from "next";
import Header from "@/components/Tools/Header";
import { Footer } from "@/components/Tools/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <div>
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="md:pt-16 pt-8 flex-1">{children}</main>
      <Footer />
    </div>
  );
}
