import type { Metadata } from "next";
import Header from "@/components/Tools/Header";
import { Footer } from "@/components/Tools/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <main className="pt-16">{children}</main>
      <Footer />
    </div>
  );
}
